package com.workout.sixpacksabs.helper;

import android.content.Context;

/**
 * Created by AdnanAli on 8/25/2016.
 */
public class AppConstant {
    public static final String USER_EEA = "user_country";
    public static final String IS_FIRST_RUN = "first_run";
    public static final boolean IS_DEBUG = true;
    public static final String SNOOZE_REMINDER = "snooze_reminder";
    public static final String SNOOZE_TIME = "snooze_time";
    public static final String SNOOZE_NOTIFICATION = "snooze_notification";
    public static final String REMINDER_DAILY_NOTIFICATION_TAG = "daily_reminder";
    public static final String ALARM_RECEIVER_INTENT_TRIGGER = "com.workout.sixpacksabs.alarm.action.trigger";
    public static final String PRIMARY_CHANNEL = "default";
    public static final String WORKOUT_PLAN_PATH = "workout_json/plan.json";
    public static final String WORKOUT_RECOMENDED_PATH = "workout_json/recomended.json";
    public static final String FRUIT_JSON_PATH = "workout_json/fruits.json";
    public static final String EXERCISE_JSON_PATH = "workout_json/exercises_detail.json";
    public static final String CATEGORY_JSON_PATH = "workout_json/categories.json";
    public static final String BELLY_ABS = "Belly_Fat";
    public static final String PERFECT_ABS = "Perfect_Abs";
    public static final String SIX_PACK_ABS = "Six_Pack";
    public static final String CATEGORY_TYPE = "category_type";
    public static final String DAY_NUMBER = "day_number";
    public static final String DAY_HOUR_NOTIFY = "day_hour";
    public static final String DAY_MINUTE_NOTIFY = "day_minute";
    public static final String PLAN_NUMBER = "plan_number";
    public static final String ACTION_TYPE = "action_type";
    public static final String NOTIFICATION_ENABLE = "enable_daily_reminder";
    public static final String LANGUAGE = "selected_language";
    public static final String ENGLISH = "English";
    public static final String FRENCH = "French";
    public static final String PORTUGUESE = "Portuguese";
    public static final String RUSSIAN = "Russian";
    public static final String GERMAN = "German";
    public static final String ARABIC = "Arabic";
    public static final String SPANISH = "Spanish";
    public static final String LOCALE_ENGLISH = "en";
    public static final String LOCALE_FRENCH = "fr";
    public static final String LOCALE_PORTUGUESE = "pt";
    public static final String LOCALE_RUSSIAN = "ru";
    public static final String LOCALE_GERMAN = "de";
    public static final String LOCALE_ARABIC = "ar";
    public static final String LOCALE_SPANISH = "es";
    public static final int GET_ENGLISH = 0;
    public static final int GET_FRENCH = 1;
    public static final int GET_GERMAN = 2;
    public static final int GET_PORTUGUESE = 3;
    public static final int GET_RUSSIAN = 4;
    public static final int GET_ARABIC = 5;
    public static final int GET_SPANISH = 6;
    public static final String ASSETS_IMAGES = "file:///android_asset/images/";
    public static final String GOOGLE_FIT_ID = "658829123037-lcd8tfde1efq3h8k2bhiavoborgcg3up.apps.googleusercontent.com";
    public static final String COMPLETED = "completed_day";
    public static final String INCOMPLETED = "incompleted_day";
    public static final String UNKNOWN_TYPE = "unknown_type";
    public static final String INPROGRESS = "inprogress_day";
    public static final String FAT_CATEGORY = "belly_fat_category";
    public static final String BUTT_CATEGORY = "butt_category";
    public static final String FRUITS_CATEGORY = "healthy_fruits";
    public static final String EASY_PLAN = "easy_plan";
    public static final String MEDIUM_PLAN = "medium_plan";
    public static final String HARD_PLAN = "hard_plan";
    public static final String CUSTOM_PLAN = "custom_plan";
    public static final String SELECTED_CATEGORY = "selected_category";
    public static final String SELECTED_PLAN = "selected_plan";
    public static final int ALL_DAYS = 15;
    public static final String CALC_NAME = "name";
    public static final String CALC_GENDER = "gender";
    public static final String CALC_WEIGHT = "weight";
    public static final String CALC_MASS = "mass";
    public static final String CALC_AGE = "age";
    public static final String CALC_FEET = "feets";
    public static final String CALC_INCHES = "inchs";
    public static final String CALC_BMR = "bmr";
    public static final String CALC_BMI = "bmi";
    public static final String MIME_TYPE = "text/html";
    public static final String ENCODING = "charset=utf-8";
    public static final String ENCODE_SHORT = "UTF-8";
    public static final String TTS_UNMUTE = "unmute_tts";
    public static final String DATE_FORMAT_TEXT = "yyyy-MM-dd";
    public static final String DATE_FORMATE_DIGIT = "dd M yyyy";
    public static final float POUND_RATE = 2.20f;
    public static final long TIME_INTERVAL_DAY = 86400000;
    public static final int CLOCK_TYPE = 24;
    public static final int TOTAL_DAYS = 21;
    public static String  IS_ADS_DISABLED = "remove_ads";
    public static Context mContext;
    public static String GOOGLE_PLAY_URL = "https://play.google.com/store/apps/details?id=";
    public static String MORE_APPS_URL = "https://play.google.com/store/apps/developer?id=Theta+Mobile";
    public static String WORKOUT_JSON_STRING;
    public static String FRUIT_JSON_STRING;
    public static String RECOMMEND_JSON_STRING;
    public static boolean SHOW_ADS = false;
    public static boolean LANGUAGE_CHANGED = false;
    public static String BASE_OBJECT = "base_object";
    public static String FRUIT_OBJECT = "fruit_object";
    public static String CATEGORY_OBJECT = "category_object";
    public static String EXERCISE_OBJECT = "exercise_object";
    public static String PLAN_OBJECT = "plan_object";

}